### ISSUE TITLE
PostgresqlConnectionConfiguration missing sslMode property 

### ISSUE THREAD

**Issue by slawek-mazur** [r2dbc/r2dbc-postgresql#101]
I am building a small service for which I use spring webflux together with r2dbc-postgresql. When I try to connect to db, Azures postgres which by default enforces SSL and there's nothing I can do about it, connection fails with following exception/error:

`SSL connection is required. Please specify SSL options and retry.`

There are four possible values for **SSL mode**: allow, prefer, require, disable. 

Error:

> 2019-04-24 22:10:46.395 ERROR 1232 --- [actor-tcp-nio-1] i.r.p.client.ReactorNettyClient          : Error: SEVERITY_LOCALIZED=FATAL, CODE=28000, MESSAGE=SSL connection is required. Please specify SSL options and retry., FILE=auth.c, LINE=481, ROUTINE=ClientAuthentication

**Comment by cambierr** [comment]
TLS isn't supported yet by r2dbc but an issue already exists about that: https://github.com/r2dbc/r2dbc-postgresql/issues/59
