### ISSUE TITLE
DateCodec delegation to InstantCodec cannnot read columns with date type 

### ISSUE THREAD

**Issue by MarioAriasC** [r2dbc/r2dbc-postgresql#109]
`DateCodec` delegates its implementation to `InstandCodec` but
when is trying to read a column of type `date`; `InstandCodec` fails to convert it as the parameter `type` is `DATE` and not `TIMESTAMP`.

```java
    @Override
    boolean doCanDecode(Format format, PostgresqlObjectId type) {
        Assert.requireNonNull(format, "format must not be null");
        Assert.requireNonNull(type, "type must not be null");

        return FORMAT_TEXT == format && TIMESTAMP == type;
    }
```

```
java.lang.IllegalArgumentException: Cannot decode value of type java.util.Date
	at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:96) ~[r2dbc-postgresql-1.0.0.M7.jar!/:na]
	at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:83) ~[r2dbc-postgresql-1.0.0.M7.jar!/:na]
```

**Comment by MarioAriasC** [comment]
If anyone has the same problem you can do a cast as a workaround:

```sql
select my_date_column::timestamp from my_table
```

**Comment by Squiry** [comment]
Take a look at [this](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/test/java/io/r2dbc/postgresql/codec/CodecIntegrationTest.java#L155).
I believe you've used `row.get("date", Date.class)`, but you should use `row.get("date", LocalDate.class)` instead.

**Comment by mp911de** [comment]
There are in general issues with date handling. `TIMESTAMP` is considered internally `Instant` but Postgres docs say that `TIMESTAMP` (also `TIME` and `DATE` types) are timezone-local so they need to map to `LocalDate`/`LocalTime`/`LocalDateTime`. `Date` is then a zone-local representation of `LocalDateTime`.
