### ISSUE TITLE
Array codecs missing during `canDecode(..)` implementation

### ISSUE THREAD

**Issue by JoseLion** [r2dbc/r2dbc-postgresql#113]
I'm trying to get a column of type `TEXT[]` in PostgreSQL so I'm mapping it in my entity as `String[]`. Everything worked as expected until I added the `String[]` filed to my entity and database, after that I got the following error:
```
Caused by: java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Object
	at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:96) ~[r2dbc-postgresql-1.0.0.M7.jar:na]
	at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:83) ~[r2dbc-postgresql-1.0.0.M7.jar:na]
	at io.r2dbc.spi.Row.get(Row.java:46) ~[r2dbc-spi-1.0.0.M7.jar:na]
	at org.springframework.data.r2dbc.convert.MappingR2dbcConverter$RowParameterValueProvider.getParameterValue(MappingR2dbcConverter.java:426) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]
	... 81 common frames omitted
```

I noticed the error said the data type was `java.lang.Object`, but it seems this comes from `org.springframework.data.r2dbc` using the default `get(..)` method from the `Row` interface. However, I debugged a bit around the [canDecode(..)](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/AbstractCodec.java#L38) implementation in [AbstractCodec.java](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/AbstractCodec.java) (in [this](https://github.com/r2dbc/r2dbc-postgresql/blob/f8a358141089de9e47f4e73f672e2db7f6df1f3c/src/main/java/io/r2dbc/postgresql/codec/AbstractCodec.java#L43) line to be precise), and I notices the following codecs are not being tested (from [DefaultCodecs.java](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/DefaultCodecs.java)):
```java
new ShortArrayCodec(byteBufAllocator),
new StringArrayCodec(byteBufAllocator),
new IntegerArrayCodec(byteBufAllocator),
new LongArrayCodec(byteBufAllocator)
```

I'm not really sure why they are not being tested, but I hope this information helps to find the source of the issue.

Hope a fix can be merged and released soon. Also, thanks in advance 🙂

**Comment by JoseLion** [comment]
**UPDATE**

I think I found the source of the issue: In [AbstractArrayCodec.class](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/AbstractArrayCodec.java) there's the method `isTypeAssignable(..)` which checks if the type passed is an array ([here](https://github.com/r2dbc/r2dbc-postgresql/blob/f8a358141089de9e47f4e73f672e2db7f6df1f3c/src/main/java/io/r2dbc/postgresql/codec/AbstractArrayCodec.java#L110)):
```java
if (!type.isArray()) {
  return false;
}
```

But given `io.r2dbc.spi` uses the default `get(..)` method from `Row` interface (as explained above), then `type` will always be of type `java.lang.Object`. Hence `Object.class.isArray()` will always be `false` 😞 

I think the question would be why `io.r2dbc.spi` is not using the `get(..)` method that allows to pass the specify type? It seems the bug is on `io.r2dbc.spi` side so if you guys see fit, this issue may be closed and I'll open another one in `io.r2dbc.spi` repository 🙂 

cc. @nebhale

**Comment by eichhornchen27** [comment]
I've faced the same issue today. Are there any updates?

cc. @nebhale
