### ISSUE TITLE
Deprecate LEGACY_POSTGRESQL_DRIVER

### ISSUE THREAD

**Issue by gregturn** [r2dbc/r2dbc-postgresql#124]
In light of #117, flag that this constant is deprecated and not for "new" efforts.

**Comment by gregturn** [comment]
To add a deprecation warning would require removing https://github.com/r2dbc/r2dbc-postgresql/blob/master/pom.xml#L175 from the build.

**Comment by mp911de** [comment]
Including deprecated elements doesn't feel right for a "new" piece of software. I suggest that we silently support the `postgres` scheme. It does not impose severe constraints of efforts, it is just another conditional.
