### ISSUE TITLE
StringCodec doCanDecode test wrong

### ISSUE THREAD

**Issue by KaRkY** [r2dbc/r2dbc-postgresql#13]
`StringCodec` at line 51 tests if return type from database is:
`TEXT == format && VARCHAR == type`
I think it should be:
`TEXT == format || VARCHAR == type`

**Comment by nebhale** [comment]
This is correct as implemented.  `format` describes the encoding of the data in the frame, and has nothing to do with the contents being tested (e.g. integers are transmitted in `TEXT` form in some cases).  So this line ensures that the encoding is `TEXT` and the type is `VARCHAR` (the string type).

**Comment by KaRkY** [comment]
Oh OK did not know that got to that conclusion with debuging issue #14 then this issue can be closed.
