### ISSUE TITLE
TEXT ARRAY values containing white space are wrapped in ""

### ISSUE THREAD

**Issue by NikolajLeischner** [r2dbc/r2dbc-postgresql#135]
To ensure its output is unambiguous, Postgres wraps elements of text arrays in quotes in certain cases. Refer to the documentation: https://www.postgresql.org/docs/9.6/arrays.html (Section 8.15.6. Array Input and Output Syntax)

The r2dbc-postgres codec does not take that into account and returns text array values as they are given by Postgres. This means if I insert the array `["some", "white space"]` and retrieve it, I get `["some", ""white space""]`.

I think this should be handled at the level of r2dbc-postgres.

**Comment by mp911de** [comment]
Can you retry whether the issue persists? `StringArrayCodec` is now also enabled for binary format decoding but that should not affect array decoding.

If so, please provide a bit of code to reproduce the issue using R2DBC SPI.

**Comment by NikolajLeischner** [comment]
I'll probably be able to re-check this before the end of this week and will get back to you once I do :)

**Comment by NikolajLeischner** [comment]
Confirmed, after updating from `1.0.0.M7` to the current snapshot, the issue is gone.
