### ISSUE TITLE
Timestamp rounded up when sent to the database 

### ISSUE THREAD

**Issue by rjaros** [r2dbc/r2dbc-postgresql#137]
When sending `LocalDateTime` value to the `timestamp(0) without time zone` column in PostgreSQL database, the time is rounded up to the nearest second. E.g. the value "2019-08-21T20:02:32.857" is saved as "2019-08-21 20:02:33" in db. But it's wrong - I can imagine getting the wrong day, month or even year in special cases.

**Comment by mp911de** [comment]
The precision parameter value`0` in `TIMESTAMP(0)` is what leads to rounding. As per Postgres doc:

> precision parameter, which causes the result to be rounded to that many fractional digits in the seconds field. Without a precision parameter, the result is given to the full available precision.

See also https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-DATETIME-INPUT.

Therefore, this doesn't seem to be a driver issue. Can you please retest with a higher precision value?

**Comment by rjaros** [comment]
You are correct. It's the precision parameter.

**Comment by mp911de** [comment]
Thanks for the confirmation. Closing this ticket as there's nothing to do in the driver.
