### ISSUE TITLE
ExtendedQueryPostgresqlStatement emits Result before processing execution errors

### ISSUE THREAD

**Issue by killaitis** [r2dbc/r2dbc-postgresql#148]
Note: the following issue was observed with `spring boot 2.2.0.M5`, `spring 5.2.0.RC2` and `r2dbc-*-0.8.0.BUILD-SNAPSHOT`. 

If an exception is caught inside `TransactionalOperator::transactional` (in the example below it is a duplicate key error), the exception ist not always handled correctly forwarded down the Flux. If the statement that failed is a `SimpleQuery` without bindings, the error is handled correctly, but if it is an `ExtendedQuery`, the ROLLBACK query seems to be mixed with the failed query (at least this is what I could debug with my limited knowledge) and none of the queries ever succeeds. Instead `reactor.core.publisher.Operators` write a log message `Operator called default onErrorDropped` and the process is stuck. 

When switching to `r2dbc-*-0.8.0.M8` the code below will work, but due to bug #139 (which is not fixed in M8) the transaction will not be rolled back anyway, so this is not an indication that M8 works correctly. 

Here is some code to reproduce the issue:

```java
    @Test void transactionalOperatorShouldForwardError() {
        TransactionalOperator operator = TransactionalOperator.create(new R2dbcTransactionManager(connectionFactory));

        Mono.empty()
                // this works
//                .then(databaseClient.execute("insert into foo (id) values(1)").fetch().rowsUpdated().log("INSERT 1"))
//                .then(databaseClient.execute("insert into foo (id) values(1)").fetch().rowsUpdated().log("INSERT 2"))

                // this doesn't work
                .then(databaseClient.execute("insert into foo (id) values(:id)").bind("id", 1).fetch().rowsUpdated())
                .then(databaseClient.execute("insert into foo (id) values(:id)").bind("id", 1).fetch().rowsUpdated())

                .as(operator::transactional)

                .as(StepVerifier::create)
                .expectError() // the code in the transaction throws indeed a DataIntegrityViolationException, but it is not forwarded by operator::transactional
                .verify(Duration.ofSeconds(10)); // instead the code is stuck and the test terminated by the timeout.
    }
```

If this issue is regarded as being related more to spring-boot-r2dbc, please move it there.

**Comment by mp911de** [comment]
This looks like an issue in `TransactionalOperator`, spring-projects/spring-framework#23304. Can you please switch  from `Mono` to `Flux` or invoke the database functionality in `TransactionalOperator.execute(…)`?

**Comment by killaitis** [comment]
Changed code to 

```java
        operator.execute(tx -> Mono.empty()
                .then(databaseClient.execute("insert into foo (id) values(:id)").bind("id", 1).fetch().rowsUpdated())
                .then(databaseClient.execute("insert into foo (id) values(:id)").bind("id", 1).fetch().rowsUpdated())
        )
```

No change in behaviour.

**Comment by killaitis** [comment]
I added Flux.log() to the executed statements and the result is this:

```
INSERT.onSubscribe()
INSERT.request(256)
INSERT.cancel()
INSERT.onNext() // why next, not error?????
INSERT.cancel()
TransactionalOperatorImpl        : Initiating transaction rollback on application exception
ROLLBACK.onSubscribe()
ROLLBACK.request(unbounded)
INSERT.onError // why here????
reactor.core.publisher.Operators         : Operator called default onErrorDropped (duplicate key value violates unique constraint)
```

Then the process is stuck. Unfortunately I cannot identify which of the two INSERTs is writing the log.

**Comment by killaitis** [comment]
This is what happens when not using the bind() (`SimpleQueryPostgresqlStatement`):

```
INSERT.onError()
INSERT.cancel()
TransactionalOperatorImpl        : Initiating transaction rollback on application exception
ROLLBACK.onSubscribe()
ROLLBACK.request(unbounded)
ROLLBACK.onNext()
ROLLBACK.request(1)
ROLLBACK.onComplete()
```

Looks plausible.

**Comment by mp911de** [comment]
With cancellations and transaction, we typically have an issue because downstream operators do not await completion. I need to debug through this. Alternatively, setting a breakpoint in the Postgres statement classes on `execute(…)` should show which statements are affected.

You can get more debug logs via `Hooks.onOperatorDebug()`

Can you reproduce that issue with plain R2DBC code so there's no Spring used?

**Comment by killaitis** [comment]
Issue can be triggered using plain R2DBC:

```java
        Mono.from(connectionFactory.create()).flatMap(connection -> Mono.empty()
                .then(Flux.from(connection.beginTransaction()).then())

                // does not work
                .then(Flux.from(connection.createStatement("insert into foo (id) values($1)").bind("$1", 1).execute()).flatMap(Result::getRowsUpdated).reduce(0, Integer::sum))
                .then(Flux.from(connection.createStatement("insert into foo (id) values($1)").bind("$1", 1).execute()).flatMap(Result::getRowsUpdated).reduce(0, Integer::sum))

                // works
//                .then(Flux.from(connection.createStatement("insert into foo (id) values($1)").bind("$1", 1).execute()).then())
//                .then(Flux.from(connection.createStatement("insert into foo (id) values($1)").bind("$1", 1).execute()).then())

                // works
//                .then(Flux.from(connection.createStatement("insert into foo (id) values(1)").execute()).flatMap(Result::getRowsUpdated).reduce(0, Integer::sum))
//                .then(Flux.from(connection.createStatement("insert into foo (id) values(1)").execute()).flatMap(Result::getRowsUpdated).reduce(0, Integer::sum))

                .then(Flux.from(connection.commitTransaction()).then())

                .onErrorResume(ex -> Mono.from(connection.rollbackTransaction()).then(Mono.error(ex)))
        )
                .as(StepVerifier::create)
                .expectError(PostgresqlServerErrorException.class)
                .verify(Duration.ofSeconds(10));
```

**Comment by mp911de** [comment]
Thanks for the example. Feel free to investigate further on the issue. Alternatively, we can look later next week into the issue.

**Comment by killaitis** [comment]
Small status update: I did not manage to do any further work on this issue as I‘m currently on vacation. I‘ll resume investigation next week. 

@mp911de did you happen to get any insights on the issue? Do we consider this issue to be a blocker (after all, this bug will let each and every failed transaction hang indefinitely)?

**Comment by mp911de** [comment]
I wasn't entirely able to reproduce the issue. What I found so far is that `ExtendedQueryPostgresqlStatement` emits a `PostgresqlResult` and then it processes `ErrorResponse`. Running a `Bind` and `Exeucte` that fails emits `BindComplete` and `NoResponse` frames before `ErrorResponse`. This leads to emitting `PostgresqlResult` instead of emitting an error. 

Running the example makes it visible that an error signal was dropped and I assume that is the reason for why we see the code fail.

**Comment by killaitis** [comment]
I can confirm that the current master does not show the issue anymore. So I support your assumption and the issue is rightfully closed.
