### ISSUE TITLE
column name escaping not working with default `findAll` method

### ISSUE THREAD

**Issue by cambierr** [r2dbc/r2dbc-postgresql#167]
Given a model class containing:
```java
    @Column(value = "end")
    private long end;
```
the default `findAll` method doesn't work since it doesn't escape the column whose name is `end`.

If escaping the name in the column like so:
```java
    @Column(value = "\"end\"")
    private long end;
```
Then the mapper can't convert the rows to entities anymore.

For now, the only obvious fix seems to redefine the `findAll` method in the repository interface with something like `@query("select * from myEntity")`

**Comment by mp911de** [comment]
Can you please file this issue in https://github.com/spring-projects/spring-data-r2dbc? The Postgres driver does not apply escaping. Spring Data R2DBC should escape column names.

**Comment by cambierr** [comment]
Sorry for this one, wrong project indeed
