### ISSUE TITLE
Mapping result error is not propagating upstream

### ISSUE THREAD

**Issue by calvernaz** [r2dbc/r2dbc-postgresql#17]
After playing a bit with the driver I notice that when an error happens while mapping a row the error wasn't being pushed upstream - so I registered a `doOnError` and propagate it upwards.

However the upstream hook `doOnError` ("2. doOnError") never gets called . Am I doing something wrong ?

```
r2dbc.withHandle(handle ->
     handle
           .select(SELECT_INNER_JOIN)
           .mapResult(result -> 
                 result.map((rw, rm) -> rw.get("product_id", Integer.class))) // mapping
            .doOnError(Mono::error) // push error upstream
     )
     .doOnError(throwable -> LOG.error("2. doOnError", throwable))
     .subscribe();
```

**Comment by nebhale** [comment]
Confirmed.

**Comment by nebhale** [comment]
Let me retract that.  I just ran the following test:

```
@Test
void test() {
    getJdbcOperations().execute("INSERT INTO test VALUES (100)");

    this.r2dbc.withHandle(handle -> handle
        .select("SELECT value FROM test")
        .mapResult(result -> result.map((rw, rm) -> rw.get("product_id", Integer.class)))
    )
        .log("stream.alpha")
        .as(StepVerifier::create)
        .verifyError();
}
```

And the result was a passed test with viable logging:

```
09:58:38.763 main               stream.alpha                                            onSubscribe(MonoFlatMapMany.FlatMapManyMain)
09:58:38.765 main               stream.alpha                                            request(unbounded)
09:58:39.497 reactor-tcp-nio-1  stream.alpha                                            onError(java.lang.IllegalArgumentException: Column name 'product_id' does not exist in column names [value])
09:58:39.499 reactor-tcp-nio-1  stream.alpha                                            
java.lang.IllegalArgumentException: Column name 'product_id' does not exist in column names [value]
	at io.r2dbc.postgresql.PostgresqlRow.getColumn(PostgresqlRow.java:131)
	at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:77)
	at io.r2dbc.client.PostgresqlExample.lambda$null$0(PostgresqlExample.java:83)
	at io.r2dbc.postgresql.PostgresqlResult.lambda$map$0(PostgresqlResult.java:69)
...
```

Your use of `.subscribe()` directly seems suspect though.  There's nothing that would hold open the process (if this was in a small `main` method, the JVM would stop before the error returned).  You'll need something like a `CountDownLatch`, Reactor's `StepVerifier` or even (in the worst case) `blockLast()` to hold open the thread long enough for an error to happen.

**Comment by calvernaz** [comment]
I was using `Thread.sleep` to avoid the main thread to slip away. But I notice I was swalloing the error with `doOnError` - so that was a problem. 

I changed a bit the example above to use a `CountDownLatch` to avoid ambiguity and instead of `doOnError` to `onErrorResume` where I throw an exception.

Your test show the error I have in the downstream subscriber - my question is/was can I push it upstream?

```		
CountDownLatch latch = new CountDownLatch(2);
PostgresqlConnectionConfiguration configuration =
		PostgresqlConnectionConfiguration.builder()
				                                 .host("localhost")
				                                 .database("test-db")
				                                 .username("postgres")
				                                 .password("postgres")
				                                 .build();
		
R2dbc r2dbc = new R2dbc(new PostgresqlConnectionFactory(configuration));
		
r2dbc.withHandle(handle ->
    handle
        .select(SELECT_INNER_JOIN)
        .mapResult(result -> result .map((rw, rm) -> rw.get("product_id", Integer.class)))
	.onErrorResume((Function<Throwable, Publisher<Integer>>) throwable -> {
		latch.countDown();
		throw new IllegalArgumentException();
	})
    )
    .doOnError(throwable -> {
        LOG.error("2. doOnError", throwable);
	latch.countDown();
    })
    .subscribe();
		
latch.await();
```

[RawInnerJoinSelect.txt](https://github.com/r2dbc/r2dbc-postgresql/files/2480144/RawInnerJoinSelect.txt)

**Comment by nebhale** [comment]
I'm not sure precisely what you're aiming to do.  In general, one of the tenants of reactive programming  is that subscriptions go up, items, error, and completion come down.  So if an error is generated as part of mapResult, only the things that happen after it in the flow (i.e. below in the way most code is written) would see it.  The content above has already executed and is in the past, so you don't send errors up to it.  What is the end result that you're trying to achieve?

**Comment by nebhale** [comment]
Also, just for reference a more idiomatic use of `CountDownLatch` (because your code still releases the thread too early, would be:

```java
CountDownLatch latch = new CountDownLatch(1);

r2dbc.withHandle(handle ->
    handle
        .select(SELECT_INNER_JOIN)
        .mapResult(result -> result.map((rw, rm) -> rw.get("product_id", Integer.class)))
        .onErrorResume((Function<Throwable, Publisher<Integer>>) throwable -> {
            throw new IllegalArgumentException();
        })
)
    .doOnError(throwable -> {
        LOG.error("2. doOnError", throwable);
    })
    .subscribe(System.out::println, t -> {
        t.printStackTrace();
        latch.countDown();
    }, latch::countDown);

latch.await();
```

**Comment by calvernaz** [comment]
Actually in mine is never releasing it - the counter is at 2. I'm aware of that version - I kept my `subscribe` clean for visualization.

This all started with the question if the exception thrown on the downstream subscriber would ever be caught on the outside `doOnError`.

**Comment by nebhale** [comment]
> if the exception thrown on the downstream subscriber would ever be caught on the outside `doOnError`.

The code as displayed here doesn't ever throw an exception on the downstream subscriber so I'm not sure how this example would prove or disprove that.  If your question is whether the exceptions thrown by either `result.map((rw, rm) -> rw.get("product_id", Integer.class))` or `throw new IllegalArgumentException();` are encountered by `LOG.error("2. doOnError", throwable);`, then the answer is yes.  The first will be swallowed by the `onErrorResume` and the second one will be propagated out as it's an error generated by the fresh stream.

**Comment by calvernaz** [comment]
I'm calling downstream subscriber to the `onErrorResume` where I throw an exception.

>  If your question is whether the exceptions thrown by either result.map((rw, rm) -> rw.get("product_id", Integer.class)) or throw new IllegalArgumentException(); are encountered by LOG.error("2. doOnError", throwable);, then the answer is yes. 

Yes, that's my question and it's not happening.

> The first will be swallowed by the onErrorResume and the second one will be propagated out as it's an error generated by the fresh stream.

Those are exactly my expectations, however is not happening.

I attached a file above with the complete example.

**Comment by calvernaz** [comment]
I get something similar if I throw something intentionally wrong. But not in my specific case - if I have time I'll try to dig this out.

**Comment by nebhale** [comment]
One thing to look at is whether the select statement actually returns any rows.  I had to add that `getJdbcOperations().execute("INSERT INTO test VALUES (100)");` just to trigger the failure in the first place.

**Comment by calvernaz** [comment]
It's not the case here, I have a full schema with data and I can debug the results.

**Comment by chang-chao** [comment]
@calvernaz In the result of your SQL, the `product_id` column does exist( `order_details.product_id` ),  so there should not be mapping errors.  
Would you please look at that?

**Comment by calvernaz** [comment]
@chang-chao it does exist (see image below). The error that I'm forcing is a type cast error.  

<img width="1126" alt="screenshot 2018-10-22 at 19 37 30" src="https://user-images.githubusercontent.com/1269712/47311564-fcee0900-d631-11e8-9101-ab4df2afac57.png">

**Comment by chang-chao** [comment]
@calvernaz Do you mean that the type of product_id column in DB is not int and you expect a type casting error?
The IntCodec uses parseInt method to parse the value, so if the value of the column value can be converted to an integer, no error will happen.

**Comment by chang-chao** [comment]
> Yes I do expect and in fact I got it.
Can you post the detail of the exception you got ?
And which version of r2dbc are you using?

**Comment by chang-chao** [comment]
@calvernaz It is strange, I even created a [sample repository](https://github.com/chang-chao/r2dbc-postgresql-issue17), with almost the same code with the one you gave above,  where  the two `doOnError` s do get called.

**Comment by calvernaz** [comment]
The difference is that I'm trying to move the error upstream and maybe it isn't possible.

[example repository](https://github.com/calvernaz/r2dbc-tests)

**Comment by chang-chao** [comment]
@calvernaz What you tried to do should have been done. you can try limiting the query result row count by adding a `limit 10`  and check the result.

@nebhale In the reproducing case, the query result has  2155  rows, when mapping exception occurs for the first row , client sends `Terminate` , data rows continues to come and `CommandComplete` and `ReadyForQuery`  are  received after row completes, and the thread is waiting for them and  the mapping exception is not propagated downstream.

In the cases that not reproduce the issue, when the number of returning rows is small, Postgresql server does send the `CommandComplete` and `ReadyForQuery`  after all rows are sent.

**Comment by chang-chao** [comment]
@calvernaz The issue should be fixed by #29 , would you please check it using the snapshot version of r2dbc-postgresql ?

**Comment by calvernaz** [comment]
I'm afraid it doesn't fix the issue.

**Comment by chang-chao** [comment]
@calvernaz It seems that when you tested 6 hours ago, the BUILD-SNAPSHOT jar compiled from the latest source was not pushed to maven snapshot repository.
Now I confirmed that it has been pushed  now .
Make sure to force a maven snapshot update by using the command `mvn clean compile -U` or some other ways.

**Comment by calvernaz** [comment]
Yey, this indeed fixes the issue. Thanks @chang-chao and @nebhale

**Comment by nebhale** [comment]
Thanks to @chang-chao especially!
