### ISSUE TITLE
1.0.0 M7 does not work with spring-data-r2dbc 1.0.0 RC1

### ISSUE THREAD

**Issue by odfsoft** [r2dbc/r2dbc-postgresql#180]
when I try to update to the latest version of r2dbc-postgres 1.0.0 M7 while using the latest version of spring-data-r2dbc, I get no response for my repositories.

sample project: 
works well
```
<spring-data-r2dbc.version>1.0.0.M1</spring-data-r2dbc.version>
<r2dbc-postgres.version>1.0.0.M7</r2dbc-postgres.version>
```

but not:
```
<spring-data-r2dbc.version>1.0.0.RC1</spring-data-r2dbc.version>
<r2dbc-postgres.version>1.0.0.M7</r2dbc-postgres.version>
```

Dependencies:
```
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-r2dbc</artifactId>
			<version>${spring-data-r2dbc.version}</version>
		</dependency>
		<dependency>
			<groupId>io.r2dbc</groupId>
			<artifactId>r2dbc-postgresql</artifactId>
			<version>${r2dbc-postgres.version}</version>
		</dependency>
```
sample project: https://github.com/odfsoft/spring-boot-guess-game/tree/r2dbc-issue

**Comment by mp911de** [comment]
Please upgrade to 0.8.0.RC2. 0.8 is the latest release after we decided to adjust version numbering:

* https://r2dbc.io/2019/05/13/r2dbc-0-8-milestone-8-released
* https://r2dbc.io/2019/10/07/r2dbc-0-8-rc2-released

**Comment by odfsoft** [comment]
Thank you so much, it was indeed confusing to see from 1.0.0M7 to 0.8.0.
