### ISSUE TITLE
Support unix domain socket connections

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-postgresql#181]
It would make sense to support unix domain sockets as connection addresses in addition to host/port-based addressing.

Using `PostgresqlConnectionConfiguration`, we could introduce a `socket(…)` configuration method to configure the socket endpoint.

For `PostgresqlConnectionFactoryProvider`, we could have a `Option.valueOf("socket")` that configures the socket to use.

Probably we don't have a good way how to configure the socket using URL-based connection strings as we assume `<host>[/<database>]` as pattern. The path does not provide any information about whether the last segment is a database name or whether it belongs to the socket. At configuration time, the socket might not even be available so a exists check cannot be used to disambiguate the string.

Related issue: spring-projects/spring-data-r2dbc#192

**Comment by mirromutth** [comment]
May be useful: `SSLSessionHandlerAdapter#operationComplete()` cast the type of `channel.remoteAddress()` result to be `InetSocketAddress` when `SSLMode` is `VERIFY_FULL`, because it need verify the hostname.

So, maybe can not support `VERIFY_FULL` when using unix domain socket.

**Comment by mp911de** [comment]
Although MySQL uses the `.sock` scheme, there's really nothing that would enforce it. So let's keep the URL variant out of scope for now. I was also wondering about SSL. Probably we don't need SSL, I haven't investigated yet what the database does if SSL is available or whether it's possible to use client certificates over unix domain sockets. Likely, SSL and domain sockets do not make sense.

**Comment by jvz** [comment]
Did you ever decide on a URL syntax for this feature?

**Comment by mp911de** [comment]
The format is: `r2dbc:postgresql:///foo?socket=/tmp/.s.PGSQL.5432`
