### ISSUE TITLE
implement binary transfer and codecs

### ISSUE THREAD

**Issue by davecramer** [r2dbc/r2dbc-postgresql#21]
Implement binary protocol
All of the codecs are TEXT only

**Comment by nebhale** [comment]
Well, the [numerics are binary](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/IntegerCodec.java#L53-L71), but I take your point on the others.  Is this a bit of expertise you can lend?

**Comment by davecramer** [comment]
yes, next on my list..
Also we need to tell the backend which oids we want in binary in the startup message.

**Comment by nebhale** [comment]
Oh, that's interesting.  One thing I'd request, just since I don't have a deep background in PostgreSQL is that either commit messages or PRs include pointers to documentation for features like that.  I wasn't aware you could even do that :)

**Comment by davecramer** [comment]
Actually I need to recant, it is sent in the prepare message to tell pg we can receive it in binary.

But sure, I'll try to document

**Comment by davecramer** [comment]
I think  https://github.com/r2dbc/r2dbc-postgresql/blob/03b53d3e802f7700bf3bcff3f62131e0e2e31906/src/main/java/io/r2dbc/postgresql/client/ExtendedQueryMessageFlow.java#L103

needs to be changed so that Describe is before the bind so that we have the RowDescriptions to be able to send the binary formats to the bind command

**Comment by mp911de** [comment]
See also #76.
