### ISSUE TITLE
On error not triggered when listen connection terminated

### ISSUE THREAD

**Issue by steven-sheehy** [r2dbc/r2dbc-postgresql#212]
## Bug Report

Fails to trigger an `onError` when the database is stopped and using postgresql listen. 

#### Versions

- Driver: `0.8.0.RELEASE`
- Database: `postgres:11.3-alpine`
- Java: 11
- OS: MacOS

#### Current Behavior

<details>
<summary>Stack trace</summary>

```
// your stack trace here
```

</details>
 
#### Table schema

<details>
<summary>Input Code</summary>

```sql
-- your SQL here;
```

</details>

#### Steps to reproduce

Run JUnit test: `R2dbcListenApplicationTests.testDisconnect()`:
https://github.com/steven-sheehy/r2dbc-listen

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Possible Solution

- Trigger an onError immediately
- Attempt reconnect automatically within some timeout, then trigger an onError if unsuccessful

**Comment by mp911de** [comment]
Probably it would make sense to send different signals when the connection was closed intentionally and unintentionally. If the server goes down, we should send `onError`. When the application gets shut down, then we would complete the stream normally (`onComplete`).

**Comment by mp911de** [comment]
That's fixed now.
