### ISSUE TITLE
Custom comparators for R2dbcRepository in Spring Data

### ISSUE THREAD

**Issue by LaoTsing** [r2dbc/r2dbc-postgresql#220]
## Feature Request

Needed custom comparators for supporting special Jsonb, Arrays and Full Text Search of PostgreSQL inline queries in Criteria builder

#### Describe the solution you'd like

As solution may be create comparators as bean and dynamic extending collection:

`enum Comparator {
		EQ, NEQ, LT, LTE, GT, GTE, IS_NULL, IS_NOT_NULL, LIKE, NOT_IN, IN,
	}`

**Comment by mp911de** [comment]
This repository contains the Postgres driver which does not come with any kind of repository abstraction. The driver uses plain SQL to interact with database statements. You want rather to file your issue in the Spring Data R2DBC repository.
