### ISSUE TITLE
Capability to disable prepared statement caching

### ISSUE THREAD

**Issue by x0a1b** [r2dbc/r2dbc-postgresql#223]
So when using Postgres with connection poolers like [pgbouncer](http://www.pgbouncer.org/) one might end up in a situation where you have to disable prepared statement caching. This is what Postgres JDBC driver allows if you set `prepareThreshold=0` in connection string. As far as I can see from [source code](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactory.java#L173) that is not possible today. Can we enable similar mechanism with `preparedStatementCache=0`; alternatively this will allow developers controlling cache size. JDBC has similar option `preparedStatementCacheQueries` I hope we can do something similar.

**Comment by Squiry** [comment]
One note: pgjdbc handles errors "prepared statement does not exist" and retries the whole process even when caching enabled. I'm not sure that poolers are the reason of this behaviour though.

**Comment by steven-sheehy** [comment]
Documentation is wrong in README and mentions -1 to disable instead of 0:
```
Determine the number of queries that are cached in each connection. The default is -1, meaning there's no limit. The value of -1 disables the cache. Any other value specifies the cache size.
```
Documentation in code looks correct:
```
Configure the preparedStatementCacheQueries. The default is {@code -1}, meaning there's no limit. The value of {@code 0} disables the cache. Any other value specifies the cache size.
```

**Comment by mp911de** [comment]
Good catch, that's fixed now.

**Comment by davecramer** [comment]
Hmmmm.... prepareThreshold=0 doesn't explicitly disable the cache preparedStatementCacheQueries=0 does that.
