### ISSUE TITLE
Add a codec for BigInteger

### ISSUE THREAD

**Issue by timve** [r2dbc/r2dbc-postgresql#233]
I would like to add support for the `BigInteger` type to the codecs.

In our project we use r2dbc in combination with code generated by jooq (based on the sql schema). When a Numeric column has a scale of 0 (the default) and has a sufficiently high precision, the generated java type for the column is a `BigInteger`. 

I would like to be able to get the column value as this type from r2dbc by adding a codec similar to the `BigDecimalCodec`.

I have currently written this codec in our own project but would like to add them to r2dbc-postgresql.

**Comment by mp911de** [comment]
Sounds like a good fit for the driver. Do you want to submit a pull request for the codec along with some tests?

**Comment by timve** [comment]
Thank you for the quick response, I have opened pull request #235 to add the codec to the driver.
