### ISSUE TITLE
Add codec for java.sql.Date and java.sql.Timestamp

### ISSUE THREAD

**Issue by timve** [r2dbc/r2dbc-postgresql#234]
I would like to add support for the `java.sql.Date` and `java.sql.Timestamp` types to the codecs.

In our project we use r2dbc in combination with code generated by jooq (based on the sql schema). When using a Date column in the schema jooq will generate the java type for the column as a `java.sql.Date`. Similar when using a Timestamp column in the schema jooq will generate the java type for the column as a `java.sql.Timestamp`.

I would like to be able to get the column values as these types from r2dbc by adding codecs similar to the `DateCodec`.

I have currently written these codecs in our own project but would like to add them to r2dbc-postgresql.

**Comment by mp911de** [comment]
Both types originate from the JDBC package java.sql. We do not have a dependency on JDBC and we don’t want to add one. Instead, R2DBC is based on java.time types that make a much better fit for date and time types. 

jOOQ is based on JDBC itself so it clearly assumes SQL date and timestamp types.

Having this type of codec in your own code (or hosted in a JDBC compatibility project) is the right place.

**Comment by timve** [comment]
Thank you for the quick response. Sounds like a valid argument, we will keep it in our own code. 

I will have another look into the jooq features to see if we could tell it to pick the new java.time types that are much nicer to work with anyway ;-).

**Comment by mp911de** [comment]
Related jOOQ ticket for non-JDBC execution engines: https://github.com/jOOQ/jOOQ/issues/6298
