### ISSUE TITLE
Add codec for Postgres enumerated types

### ISSUE THREAD

**Issue by My-** [r2dbc/r2dbc-postgresql#244]
## Feature Request
Looks like enums are not supported.

#### Is your feature request related to a problem? Please describe
Maybe I missing something, or doing something wrong but I can't make Postgres enum type work (query with SELECT, INSERT).

#### Describe the solution you'd like
Possibility to map directly to Java enum type to Postgres enum. 

#### Describe alternatives you've considered
An alternative could be to get enum value as a string.

**Comment by mp911de** [comment]
We decided to not support Java native enums within the driver as enums are a user-space feature regarding their mapping possibilities (string name, ordinal, Postgres type). You can register your own codec if you wish to do so with your specific mapping rules.

**Comment by mp911de** [comment]
Reopening this issue. The assumption back then was to make enums work with either the `VARCHAR` or a numeric codec and that's what [my previous comment was about](https://github.com/r2dbc/r2dbc-postgresql/issues/244#issuecomment-583723147).

We can make Postgres enumerated types work by providing a `EnumCodec` that takes an OID and the Java enum type so we can map enumerated values in both types. From a particular Java type we can derive the Postgres type OID. While reading, we have a reference to a Java enum and can materialize a value.
