### ISSUE TITLE
multiple usage of same collection parameter in extended query

### ISSUE THREAD

**Issue by xqfgbc** [r2dbc/r2dbc-postgresql#252]
I wanna to execute native query like below:

```sql
select user_name from user where user_id in(:userIds) and age > 35
union
select user_name from user where user_id in(:userIds) and age < 20
```
but it throw an error like this: java.lang.IllegalStateException: Bound parameter count does not match parameters in SQL statement

**Comment by mp911de** [comment]
The Postgres driver uses $1, $2, $n notation for parameters. This is likely a Spring Data issue. Can you attach the actual SQL query or  run the native query using plain R2DBC API?

**Comment by xqfgbc** [comment]
May be you are right. I found something wrong under package org.springframework.data.r2dbc.core.

**Comment by mp911de** [comment]
Indeed, Spring Data R2DBC renders a SQL statement that does not match the bindings:

```
select user_name from user where user_id in($1, $2, $3) and age > 35
union
select user_name from user where user_id in($4, $5, $6) and age < 20
```

while binding only positions `$1`, `$2` and `$3`.

**Comment by mp911de** [comment]
I filed spring-projects/spring-data-r2dbc#310 to address the issue in Spring Data R2DBC.
