### ISSUE TITLE
Support hstore as default codec

### ISSUE THREAD

**Issue by Joxit** [r2dbc/r2dbc-postgresql#268]
## Feature Request

First of all, thank you for your driver !
I started a project recently and we chose to use r2dbc. My main domain is geographic services (OpenStreetMap data) and we often use PostgreSQL and Postgis.
In this domain, there is also a type we always use, it's `hstore`, and there are no codec for this type in r2dbc-postgresql.

#### Describe the solution you'd like

`hstore` data type for storing sets of key/value pairs within a single PostgreSQL value and is not a default type in PostgreSQL, it's a module that need to be activated before the use. But it could still be a good addition.

#### Describe alternatives you've considered

I do not know if there is a large part of r2dbc users who use `hstore`, if they are few they can remain their responsibility (custom codec).
This is what I did for my project, I wrote my own Hstore codec and it works pretty well.

#### Teachability, Documentation, Adoption, Migration Strategy

I want to share what I have done with the community, because if I needed it, maybe others will be in the same case. That's why I wrote the piece of code [here](https://github.com/Joxit/r2dbc-postgresql/tree/feat/hstore-support).

- The `hstore` id is `20832` (greater than `OID_CACHE_SIZE`)
- The Java type for `hstore` is `Map<String, String>`
- We must use raw types because we cannot have the class with  parameterized type (`Codec<Map>` instead of `Codec<Map<String, String>>`).

If this add makes sens, I can publish the PR.

**Comment by mp911de** [comment]
Adding `hstore` support makes sense since it part of most (all?) Postgres distributions anyway. Happy to review a pull request. Enabling `hstore` on a particular database seems to allocate OIDs, therefore, we need to look up the `hstore` OID during the connect phase and skip the codec if `hstore` is not enabled at the time the connection was established.

**Comment by Joxit** [comment]
Oh yes the OID is not fixed, so I will need this query `SELECT oid FROM pg_catalog.pg_type WHERE typname = 'hstore'`

I post the PR now with only the codec and then the OID check.
