### ISSUE TITLE
add support for providing "search_path" connection option

### ISSUE THREAD

**Issue by 62mkv** [r2dbc/r2dbc-postgresql#271]
## Feature Request

Missing is a way to specify `search_path` in a R2DBC URL

#### Is your feature request related to a problem? Please describe

In some cases, it's useful to be able to specify search_path in the URL, as it's a database specific aspect. 

#### Describe the solution you'd like

I want to be able to specify connection URL as 

`spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres?search_path=schema1,myschema`

#### Describe alternatives you've considered

An alternative (with Spring Data) is to have a bean implementing `ConnectionFactoryOptionsBuilderCustomizer` and make it do this: 

```
    @Override
    public void customize(ConnectionFactoryOptions.Builder builder) {
        if (StringUtils.isNotBlank(schemaSearchPath)) {
            builder.option(Option.valueOf("options"), Collections.singletonMap("search_path", schemaSearchPath));
        }
    }
```

This solution is sub-optimal as normally you would use same Spring config for different databases, and with H2 (for example) it will not work, because of different Option type and different option names. Would be better to be able to address all connection-specific aspects via single configuration aspect (R2DBC URL)

**Comment by 62mkv** [comment]
also see #37 - "search_path" option is different from "schema" option

**Comment by mp911de** [comment]
I'd suggest to:

1. Switch `schema` to `search_path` instead of issuing a `SET schema=` command.
2. Add an alias `currentSchema`

This way we align with PGJDBC. Being consistent with PGJDBC is more favorable than adding another option. Feel free to submit a pull request.

**Comment by 62mkv** [comment]
Hi Mark @mp911de . you can assign it on me, I will look into it. so, to clarify, is it correct understanding that:
- rename existing "schema" option to "search_path" option;
- change implementation for this option to `SET search_path TO %s` instead of `SET SCHEMA '%s'`
- add support for "currentSchema" as an alias for "search_path" 

?

**Comment by mp911de** [comment]
> rename existing "schema" option to "search_path" option;

No, please keep the `schema` option. We do not want to break existing code.

> change implementation for this option to SET search_path TO %s instead of SET SCHEMA '%s'

Not exactly. Remove the call to `PostgresqlConnectionFactory.setSchema`. Pass on the search path to [`StartupMessageFlow`](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactory.java#L194-L195) (similar to what is done to application name).

> add support for "currentSchema" as an alias for "search_path"

Yes. Actually it's an alias for `schema` but that's probably just a detail.

**Comment by 62mkv** [comment]
well, according to https://jdbc.postgresql.org/documentation/head/connect.html: 

>currentSchema = String

> Specify the schema (or several schema separated by commas) to be set in the search-path. This schema will be used to resolve unqualified object names used in statements over this connection.

`currentSchema` is an alias for `SET search_path`, essentially.

two things more to clarify: 

1) how do we ensure that `search_path=schemaA,schemaB` will be parsed as a single `Option`? parsing happens in the R2DBC engine, as far as I can tell.. 
2) what is a proper way to implement aliasing ? should this be a separate field in `PostgresqlConnectionConfiguration` ? and if both (i.e. `currentSchema` and `search_path`) are specified in a URL, which one should prevail?

**Comment by mp911de** [comment]
Here are some further details.

0. Using connection startup attributes is sent as part of the connection handshake. Using `SET …` requires a server roundtrip so moving to startup attributes gives the driver a better startup performance.
1. URL parsing uses a query string parser that use `&` (ampersand) as delimiter for key-value pairs.
2. In options are queried in [`PostgresConnectionFactoryProvider`](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryProvider.java#L250), so the way to go is, if `schema` is not set, then check the `currentSchema` option if it is set.

**Comment by 62mkv** [comment]
just thinking out loud - what if we just parse `options` (parsed by R2DBC) to `Map` in the `PostgresqlConnectionConfiguration#createConfiguration` ? That would unblock many other options in the R2DBC URLs as well..

**Comment by 62mkv** [comment]
although, I have no idea of potential implications..
