### ISSUE TITLE
Error message for authentication failure is not very useful

### ISSUE THREAD

**Issue by davecramer** [r2dbc/r2dbc-postgresql#34]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Background

PostgreSQL returns a single [`ErrorResponse`](https://www.postgresql.org/docs/11/protocol-message-formats.html) message.  When an authentication error is returned it's not clear that this common error has occurred.

## Problem

Right now, it's not obvious when an authentication error, which is very common, has occurred.

## Solution

An `R2dbcAuthenticationException` should be created as a subclass of [`R2dbcException`](https://github.com/r2dbc/r2dbc-spi/blob/master/r2dbc-spi/src/main/java/io/r2dbc/spi/R2dbcException.java) to indicate that an authentication error has occurred.  This type should then be returned when the [`ReactotNettyClient`](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java#L72-L76) encounters a `28P01` error code message.

## Steps to fix

- [ ] Claim this issue with a comment below and ask any clarifying questions you need.
- [ ] Try to fix the issue following the steps above.
- [ ] Commit your changes and start a pull request.

## Deliverables
- [ ] `R2dbcAuthenticationException` in [`r2dbc-spi`](https://github.com/r2dbc/r2dbc-spi)
- [ ] Updated [`ConnectionFactory`](https://github.com/r2dbc/r2dbc-spi/blob/master/r2dbc-spi/src/main/java/io/r2dbc/spi/ConnectionFactory.java#L31) Javadoc indicating that this error can be emitted.
- [ ] Updated [`ReactorNettyClient`](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java) that maps `28P01` errors to an `R2dbcAuthenticationException`.

**Comment by davecramer** [comment]
It's possible that I over reacted to this after reading the whole log message.

I'm thinking that a top-level exception would be less surprising though.

**Comment by nebhale** [comment]
Yeah, I can totally get on board with that.  It's a regular enough error that's easily identifiable that it should be promoted.

**Comment by nebhale** [comment]
@uaihebert I think we came to the conclusion that while the message is clear there's enough extra noise around it, that it's not intuitive.  We should probably special-case this particular failure (maybe matching on code `28P01`) and add a subclass of `PostgresqlServerErrorException` for `PostgresqlAuthenticationFailure`.  I believe the best interception point is likely in `StartupMessageFlow` if you want to have a crack at it.

**Comment by uaihebert** [comment]
hello again @nebhale , how are you? 

I know we talked about it sometime ago, but I was able to start and finish this today. 

I know this is the first round, and suggestion are welcome. 

This is how the exception is being displayed:
![image](https://user-images.githubusercontent.com/2014377/52434805-83125a80-2b10-11e9-940a-43e02e7d49a1.png)

is this the correct idea? regards

**Comment by mp911de** [comment]
Looks good and great work. Future tip: Use code fences and paste the exception as text. This makes it possible to search for the text.

I left a few comments on your pull request #72.

**Comment by uaihebert** [comment]
thank you for the response. 

thank you also for the tip regarding the code instead of image. 

I never thought about this search possibility 😅
