### ISSUE TITLE
rename io.r2dbc.postgresql.message.Format.TEXT to io.r2dbc.postgresql.message.Format.TEXT_FORMAT

### ISSUE THREAD

**Issue by davecramer** [r2dbc/r2dbc-postgresql#36]
There is some ambiguity between import static `io.r2dbc.postgresql.message.Format.TEXT` and the `TEXT` sql type.

I'm open to some other name, but currently it is confusing.

**Comment by nebhale** [comment]
I'll go ahead and make the change, but wanted to confirm that the only place that SQL `TEXT` type is actually ever used in the driver is in the `StringCodec`.
