### ISSUE TITLE
Postgresql Schema

### ISSUE THREAD

**Issue by sixdouglas** [r2dbc/r2dbc-postgresql#37]
Is it possible to set the DB Schema in the connection?

**Comment by nebhale** [comment]
PostgreSQL uses the term “database” for what many other databases term “schemas”.  The builder [has a configurator](
https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/PostgresqlConnectionConfiguration.java#L145) for that.

**Comment by sixdouglas** [comment]
Thanks for this quick replay. :thumbsup:
But there is also a schema thing in the PostgresSql objects tree that can be set this way:
`jdbc:postgresql://host:port/database?currentSchema=schema`
is there a way to address this functionality?

**Comment by nebhale** [comment]
At issue is that what you've described is a JDBC URI which isn't something that the underlying wire-protocol understands.  I'm unclear how `currentSchema=schema` is translated into the messages sent during the [Startup Flow](https://www.postgresql.org/docs/11/protocol-flow.html#id-1.10.5.7.3).  @davecramer any insight here?

**Comment by davecramer** [comment]
@nebhale 


Current schema is much like a namespace. Typically the default schema is 'public' 

so objects can be referred to as schema.table for instance or schema.function

the "default" schema is set in the search_path. We probably should have something called setSchema which allows one to change the schema.

**Comment by nebhale** [comment]
@davecramer We’re on the same page with regards to adding the feature, my questions was how.  I’m struggling to find anything in the [protocol documentation](
https://www.postgresql.org/docs/11/protocol-flow.html#id-1.10.5.7.3) that describes how this happens on the wire.

**Comment by davecramer** [comment]
Its just SQL set search_path='newpath'

Any session GUC can be set that way

**Comment by sixdouglas** [comment]
Ok, so would have to execute a SQL statement with just "set search_path='schemaName'" right after the login and that would do the trick?

**Comment by davecramer** [comment]
I think the thing to do here is have a setSessionParameter method which
would send any name, value pair
we also need a resetSession method to reset them all for connection pools.
This may be a unique thing for postgres. I'm not sure.

Dave Cramer

**Comment by sixdouglas** [comment]
I agree with you, to be able to reset those parameters, we would have to query their values before setting them to the new one.
I don't think it is a postgres specific. For MySql you can choose to set the [autocommit](https://dev.mysql.com/doc/refman/8.0/en/innodb-autocommit-commit-rollback.html) or the [charset-encoding](https://dev.mysql.com/doc/refman/8.0/en/charset-connection.html). I guess it goes the same way with Oracle

**Comment by davecramer** [comment]
Well in postgres there is a reset which sets them to the default. How this
is implemented will be db dependent.
as far as autocommit goes this is not an option in postgres. There is no
session GUC for that, as I said this will be unique to each vendor.

Dave Cramer

**Comment by nebhale** [comment]
Just to clarify for my knowledge, `SET` isn't an SQL standard command, right?  This is something implemented by some databases to allow this kind of behavior?

**Comment by davecramer** [comment]
On Mon, 26 Nov 2018 at 12:52, Ben Hale <notifications@github.com> wrote:

> Just to clarify for my knowledge, SET isn't an SQL standard command,
> right? This is something implemented by some databases to allow this kind
> of behavior?
>

Correct, I have no clue about other databases. Keep in mind the way PG
implements schema's isn't exactly standard either

FWIW, there are bunch of others as well, and GPDB will also have a bunch of
unique requirements here.

Dave

**Comment by nebhale** [comment]
Is this something that should be available on the `ConnectionFactory` or `ConnectionConfiguration` and automatically applied to all created connections?

**Comment by nebhale** [comment]
@davecramer How is this handled in the JDBC world?

**Comment by davecramer** [comment]
@nebhale adhoc.

So where the API asks us to do something we do it, such as setSchema https://github.com/pgjdbc/pgjdbc/blob/21e126f451df667627c1cc3a0acfb3c38be45ffa/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L1515-L1532

One of the biggest problems we have is *all* of the sometimes conflicting connection options and more on the way. see https://github.com/pgjdbc/pgjdbc/issues/222#issuecomment-440242361 

I haven't had much time to really think about this, but I think if you enable what you think is relevant in  https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING (see 34.1.2. Parameter Key Words) that should keep the wolves at bay, seriously, though I don't have a good recommendation at the moment for everything you would need

**Comment by nebhale** [comment]
@sixdouglas Can you please confirm that adding the `setSchema()` to the `PostgresqlConnection` is sufficient for your needs?  Or do you need it to be part of the `PostgresqlConnectionFactoryConfiguration` type for all created connections?

**Comment by sixdouglas** [comment]
I would say that keeping it at the `PostgresqlConnection` level is suffisant for the moment. I'm planning to use it in Spring Boot so I think the easiest will be to create a datasource by Repository (like this: https://medium.com/@joeclever/using-multiple-datasources-with-spring-boot-and-spring-data-6430b00c02e7)

**Comment by nebhale** [comment]
The way I've ended up choosing to implement this is a setting on `PostgresqlConnectionConfiguration` that configures the default for all connections (this is the equivalent of the `currentSchema` parameter on the JDBC URI).  For users that would like to set it on a connection once they have that connection, directly executing the `SET SCHEMA '%s'` statement is appropriate.

**Comment by davecramer** [comment]
FYI,

SET SCHEMA is actually an alias for SET SEARCH_PATH which can have multiple
paths, typically it is $user,public by default.
There is also a RESET SCHEMA


Dave Cramer

**Comment by 62mkv** [comment]
unfortunately this does not seem to be the case: 

> SET SCHEMA is actually an alias for SET SEARCH_PATH

If I execute 
```
set search_path to mwconfig,public;
show search_path;
```

it will output 
> mwconfig, public

if I execute 
```
set schema 'mwconfig,public';
show search_path;
```

it will output 
> "mwconfig,public"

in the former case, unqualified `SELECT` from table in mwconfig will return OK, in the latter - will give an error: `SQL Error [42P01]: ERROR: relation "..." does not exist`

**Comment by davecramer** [comment]
You are correct. There is a small nuance between the two as per the docs
SET SCHEMA 'value' is an alias for SET search_path TO value. Only one schema can be specified using this syntax.

**Comment by OrangeDog** [comment]
If you want to set the schema use `schema`, if you want to set the search path use `search_path`.
Talk of aliases just muddles things. Both should be supported.

**Comment by 62mkv** [comment]
well, currently

`spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres?search_path=public,mwconfig`

does not seem to work

**Comment by 62mkv** [comment]
as has been explained by @mp911de there's currently no way to set `search_path` via R2DBC URL.

**Comment by ramneekIncepta** [comment]
> @nebhale adhoc.
> 
> So where the API asks us to do something we do it, such as setSchema https://github.com/pgjdbc/pgjdbc/blob/21e126f451df667627c1cc3a0acfb3c38be45ffa/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L1515-L1532
> 
> One of the biggest problems we have is _all_ of the sometimes conflicting connection options and more on the way. see [pgjdbc/pgjdbc#222 (comment)](https://github.com/pgjdbc/pgjdbc/issues/222#issuecomment-440242361)
> 
> I haven't had much time to really think about this, but I think if you enable what you think is relevant in https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING (see 34.1.2. Parameter Key Words) that should keep the wolves at bay, seriously, though I don't have a good recommendation at the moment for everything you would need

Can the schema be specified for the whole transaction?  I have too many schemas (tenants) can't afford to have a connection(or connection pool) dedicated to a schema.

**Comment by freddygomes** [comment]
Not sure if this helps but this is how we have it working with tenants...

```
@EnableTransactionManagement
public class R2dbcConfig extends AbstractR2dbcConfiguration {
    private final R2dbcProperties properties;

    @Bean
    @Override
    public ConnectionFactory connectionFactory() {
        ConnectionFactory connectionFactory = createPostgresConnectionFactory();
        ConnectionPool pool = pool(connectionFactory);
        return new TenantAwareConnectionFactory(pool);
    }

    private ConnectionPool pool(ConnectionFactory connectionFactory) {
        ConnectionPoolConfiguration configuration = ConnectionPoolConfiguration.builder(connectionFactory)
                .maxSize(40)
                .build();

        return new ConnectionPool(configuration);
    }

    @Bean
    ReactiveTransactionManager transactionManager(ConnectionFactory connectionFactory) {
        return new R2dbcTransactionManager(connectionFactory);
    }

    @Override
    protected List<Object> getCustomConverters() {
        return List.of(
                new MapTypeConverter()
        );
    }

    protected ConnectionFactory createPostgresConnectionFactory() {
        ConnectionFactoryOptions base = ConnectionFactoryOptions.parse(properties.getUrl());
        PostgresqlConnectionConfiguration postgresqlConnectionConfiguration = PostgresqlConnectionConfiguration.builder()
                .host(base.getRequiredValue(HOST))
                .port(Optional.ofNullable(base.getValue(PORT)).orElse(5432))
                .database(properties.getName())
                .username(properties.getUsername())
                .password(properties.getPassword())
                .codecRegistrar(EnumCodec.builder().withEnum("map_object_type", MapObjectType.class).build())
                .build();
        return new PostgresqlConnectionFactory(postgresqlConnectionConfiguration);
    }
}
```
and...
```
@RequiredArgsConstructor
public class TenantAwareConnectionFactory implements ConnectionFactory {
    private final ConnectionFactory connectionFactory;

    @Override
    public Publisher<? extends Connection> create() {
        return MultiTenantContextHolder.getContext()
                .map(MultiTenantContext::getTenantId)
                .flatMapMany(this::createConnection);
    }

    private Mono<Connection> createConnection(String tenant) {
        return Mono.from(connectionFactory.create())
                .flatMap(connection -> setTenant(connection, tenant));
    }

    private Mono<Connection> setTenant(Connection connection, String tenant) {
        final Statement statement = connection.createStatement("SET search_path = %s;".formatted(tenant));
        return Mono.from(statement.execute())
                .doOnSuccess(e -> log.debug("set tenant to {}", tenant))
                .map(e -> connection);
    }

    @Override
    public ConnectionFactoryMetadata getMetadata() {
        return connectionFactory.getMetadata();
    }
}
```
