### ISSUE TITLE
Postgres Arrays: Support for multi-dimensional arrays

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-postgresql#42]
Right now, the driver supports single-dimensional arrays. Postgres also supports multi-dimensional arrays such as `int[][]`:

```sql
CREATE TABLE tictactoe (
    squares   integer[3][3]
);
```

The driver should also support multi-dimensional arrays.

See also: https://www.postgresql.org/docs/11/arrays.html

/cc @rdegnan

**Comment by nebhale** [comment]
resolved by #54
