### ISSUE TITLE
Support custom connection SocketFactory

### ISSUE THREAD

**Issue by meltsufin** [r2dbc/r2dbc-postgresql#43]
Notably Google Cloud's Cloud SQL makes use of a [custom](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory) `javax.net.SocketFactory` for connecting to PostgreSQL.

**Comment by nebhale** [comment]
Ping @violetagg.

**Comment by mp911de** [comment]
As discussed in the linked ticket, GCP connections via [Cloud SQL Socket Factory](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory) require domain socket support. Unix domain socket support is now available with #181 and we can close this ticket now.
