### ISSUE TITLE
Investigate TLS connectivity

### ISSUE THREAD

**Issue by nebhale** [r2dbc/r2dbc-postgresql#59]

**Comment by Squiry** [comment]
@nebhale 
I've tried this one [here](https://github.com/Squiry/r2dbc-postgresql/tree/59-ssl-connectivity), but I'm not sure is it worth a pull request now. Would you mind taking a look at this?

**Comment by nebhale** [comment]
@Squiry That looks like it's headed in the right direction.  Any PR for this is going to get held until after M7 is released, so you've got some time to polish it up and play around with it.

**Comment by rinokadijk** [comment]
Does this issue include certificates? Like in: https://www.cockroachlabs.com/docs/dev/build-a-java-app-with-cockroachdb.html

**Comment by nebhale** [comment]
@rinokadijk I'd expect certificates to be managed by the standard Java SSL context APIs, at least in a first incarnation.

**Comment by cambierr** [comment]
@Squiry any chance for you to continue the work ? Otherwise, I could try to continue what you started

**Comment by Squiry** [comment]
@cambierr my branch was pretty working last time I checked. I only needed a little bit help with configuration (don't know how to do it right).

**Comment by mp911de** [comment]
From that point of view, please create a pull request so we can continue the discussion over some actual code.

**Comment by Squiry** [comment]
@mp911de #104 here it is.

**Comment by timve** [comment]
It is unclear to me what the status is of this issue and the corresponding pull request #104 can @Squiry or @mp911de (or perhaps someone else who knows) shed some light on this?
We are looking for a solution to use r2dbc with tls connections to our postgres databases and are happy to see if we can help get TLS support for postgres in r2dbc.

**Comment by mp911de** [comment]
Paging @nebhale who is the maintainer of this project.

**Comment by Squiry** [comment]
My pull request is ready for review.

**Comment by gregturn** [comment]
It's merged!

Thank you @Squiry for getting this implemented. And thanks to @mp911de for helping to pull it all together.
