### ISSUE TITLE
Example from README is not working

### ISSUE THREAD

**Issue by marekjeszka** [r2dbc/r2dbc-postgresql#68]
Usage of:
```
    ConnectionFactory connectionFactory = ConnectionFactories.get(ConnectionFactoryOptions.builder()
...
    .build());

Mono<Connection> connection = connectionFactory.create();
```
gives this compiler error: `incompatible types: org.reactivestreams.Publisher<capture#1 of ? extends io.r2dbc.spi.Connection> cannot be converted to reactor.core.publisher.Mono<io.r2dbc.spi.Connection>`

I was able to fix the error using `PostgresqlConnectionFactory` and `Mono<PostgresqlConnection>`. But it still doesn't make the example usable. Here is the error:
```
cannot find symbol
  symbol:   method createStatement(java.lang.String)
  location: variable connection of type reactor.core.publisher.Mono<io.r2dbc.postgresql.PostgresqlConnection>
```

**Comment by nebhale** [comment]
Yep, definitely won’t work (the generic needs to be `? extends Connection` at best).  @mp911de I got the example from yours and am pretty sure that the same issue exists.

**Comment by mp911de** [comment]
Documentation should rather say:

```
Publisher<? extends Connection> connectionPublisher = connectionFactory.create();

// Alternative: Creating a Mono using Project Reactor
Mono<Connection> connectionMono = Mono.from(connectionFactory.create());
```

**Comment by marekjeszka** [comment]
Thanks for clarification @mp911de.
This solves the first part. Is there also known fix to make `connection.createStatement(` usable?

**Comment by mp911de** [comment]
Using Project Reactor (or RxJava 2), you can use `flatMap`/`flatMapMany` operators to continue with the flow:

```java
connectionMono.flatMapMany(conn -> conn.createStatement(…).bind(…).execute()).flatMap(result -> result.getRowsUpdated());

connectionMono.flatMapMany(conn -> conn.createStatement(…).bind(…).execute()).flatMap(result -> result.map(…));
```

**Comment by nebhale** [comment]
@gregturn Your docs will have a similar issue.  I’ll be updating mine to match @mp911de’s once I hit the office.
