### ISSUE TITLE
Move to Californium Milestones

### ISSUE THREAD

**Issue by nebhale** [r2dbc/r2dbc-postgresql#7]

**Comment by nebhale** [comment]
Hmm.  That's not going to work.  Need the fix from https://github.com/reactor/reactor-core/issues/1033

**Comment by nebhale** [comment]
@mp911de Just a heads up that we actually need Californium.  I've upgrade to M1 for now.  Is this going to be a problem for you?

**Comment by mp911de** [comment]
Works for us. Spring Data is following the most recent Reactor upgrades and it looks like as if the Reactor Netty upgrade is already in place. I was only concerned about the fact having Californium for Reactor Core but Bismuth for Reactor Netty.
