### ISSUE TITLE
Support of rw/ro database servers

### ISSUE THREAD

**Issue by cambierr** [r2dbc/r2dbc-postgresql#70]
An interesting feature would be to be able to use a master server (for read/writes) and one-to-n slave servers (for reads only).

Is there any plans for this ?

**Comment by mp911de** [comment]
Wouldn’t that be rather a concern of a higher level component? Some sort of routing proxy that uses various connections depending on the statement.

**Comment by nebhale** [comment]
I would agree and would encourage its development.  In fact, you might be able to use https://github.com/r2dbc/r2dbc-proxy to implement such a thing.  An R2DBC driver implementation represents a factory for creating connections to a single database, and as such is an inappropriate level of abstraction to implement this feature.
