### ISSUE TITLE
Support connection pooling

### ISSUE THREAD

**Issue by cambierr** [r2dbc/r2dbc-postgresql#71]
To boost performances, it would be interesting to implement connection pooling.
Is there any plans for this ?

**Comment by mp911de** [comment]
Definitely! We require a reactive pooling foundation to build a R2DBC connection pool on top. This pre-requisite isn’t there yet so it will take a while until we get to connection pooling.

**Comment by nebhale** [comment]
It is actively being worked on as we speak though.

**Comment by kwidjaja1312** [comment]
Hi, does this ticket closed as it has been implemented or more because the comment from mp911de?

I am currently doing a research on this driver to be used in a greenfield project.

Thanks for all the work though. Looking for ward to have this enhancement soon.

**Comment by mp911de** [comment]
Thanks for this reminder. You can use connection pooling with `r2dbc-pool`. The project repo is at https://github.com/r2dbc/r2dbc-pool. Reactive connection pooling is built on top of `reactor-pool` and things are in `Flux<Development>` (pun intended). Although APIs aren't finalized yet, you can give snapshots a try:

```xml
<dependency>
  <groupId>io.r2dbc</groupId>
  <artifactId>r2dbc-pool</artifactId>
  <version>1.0.0.BUILD-SNAPSHOT</version>
</dependency>
```

**Comment by nikhilaroratgo** [comment]
please document how to use connection pool with R2dbc client. Also please give some rough idea when will we have the release?
Thanks

**Comment by nikhilaroratgo** [comment]
@mp911de I added the dependency and now I run into the problem Caused by: java.lang.NoSuchMethodError: reactor.pool.PoolBuilder.initialSize(I)Lreactor/pool/PoolBuilder;

Checked and found that reactor-pool -->PoolBuilder class does not have initialsize method.
Whereas ConnectionPool class from r2dbc-pool is trying to use this method.

**Comment by mp911de** [comment]
Please use r2dbc-pool 0.8.0.BUILD-SNAPSHOT with reactor-pool 0.0.1.BUILD-SNAPSHOT. Dependencies are currently moving fast and potentially breaking setups that worked in other versions.
