### ISSUE TITLE
Execute multiple statements in a single sql with bind params failed

### ISSUE THREAD

**Issue by rj-hwang** [r2dbc/r2dbc-postgresql#82]
Using 1.0.0.M7 execute multiple statements in a single sql with bind params failed :

```
@Test
void insertRowsByMultipleInsertIntoWithBind() {
  int[] ids = new int[]{nextId(), nextId(), nextId()};
  String sql = "insert into T(id) values($1);insert into T(id) values($2), ($3);";
  StepVerifier.create(
    connection(cache)
      .flatMapMany(c -> c.createStatement(sql)
        .bind("$1", ids[0])
        .bind("$2", ids[1])
        .bind("$3", ids[3])
        .execute())
      .flatMap(Result::getRowsUpdated)
  ).expectNext(1).expectNext(2).verifyComplete();
}
```

r2dbc-postgres error :

```
failed (expected: onNext(1); actual: onError(java.lang.IllegalArgumentException: Statement 'insert into T(id) values($1);
insert into T(id) values($2), ($3);' cannot be created. This is often due to the presence of both multiple statements and parameters at the same time.))
```

r2dbc-h2 error :

```
failed (expected: onNext(1); actual: onError(java.lang.ArrayIndexOutOfBoundsException: 3))
```

But execute success if change the bind params to raw values. Such as 'insert into T(id) values(1);insert into T(id) values(2), (3);'.

**Comment by rj-hwang** [comment]
Test case is [here](https://github.com/start-java/start-r2dbc/blob/r2dbc-postgres/issue82/src/test/java/tech/simter/start/r2dbc/ConnectionFactoryTest.java#L256).

**Comment by Squiry** [comment]
The postgresql documentation about extended query [says](https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY)

> The query string contained in a Parse message cannot include more than one SQL statement; else a syntax error is reported. This restriction does not exist in the simple-query protocol, but it does exist in the extended protocol, because allowing prepared statements or portals to contain multiple commands would complicate the protocol unduly.

r2dbc-postgres error is pretty verbose too.

**Comment by nebhale** [comment]
As @Squiry says, PostgreSQL doesn't support both binding and multiple statements (as defined by the existence of `;` in the statement) in the same invocation.  H2 has different requirements.
