### ISSUE TITLE
Add support for BLOB/CLOB types.

### ISSUE THREAD

**Issue by gregturn** [r2dbc/r2dbc-postgresql#99]
See https://github.com/r2dbc/r2dbc-spi/pull/51 for SPI details.

**Comment by nebhale** [comment]
After all this, PostgreSQL doesn't support *LOBs? 😉 

@davecramer do you have any recommendations on how to handle *LOB concepts with PostgreSQL, just assume they'll come back as `BYTEA` or `TEXT`?

**Comment by nebhale** [comment]
Resolved by 5a4de4d.
